typography_spectrum: 0.5396457326132804
color:
  brandStrength: 0.8438801730517298
  lightness: 0.16188728879205883
  saturation: 0.9374656626023352
  rhythmicContrast: 0.3441862636245787
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.33658733894117177
name: Bystro test
navigation:
  - name: Restr
    url: >-
      http://nastrencin.sme.sk/c/20240998/tatari-vypalili-trencin-odolal-len-hrad.html#ixzz4HKHQj7w5
    type: external
title: Hello
description: asdasda
